{
  "hash": "116ea807aba687256e3d0906d7b5fba0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Verify the Claim: Philly Neighbourhood Poverty Rate\"\nauthor: \"Abishek Nippani\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-summary: \"Show code\"\n    embed-resources: true\n---\n\n## Part 1\n\nWe will first load the requisite ACS data. As the article uses Five-Year Estimates for 2006-10 and 2013-17, we will call for the ACS5 data for these two survey periods.\n\nThe 2017 dataset has a poverty rate variable, \"S1701_C03_001\", but that variable does not exist in the 2010 dataset. Accordingly, we will calculate the tract-wise poverty rate as a ratio of the count of people below the poverty line (B17001_002) to the count of people for whom poverty status is determined (B17001_001). The denominator cannot be total population, as that would bias the rate downwards by including people the Census Bureau excludes from the poverty universe, such as those in institutional group quarters.\n\nWe assume the article constructed a comparable poverty rate in this manner, since a common poverty rate variable does not exist across the two periods.\n\nThe two time periods used in the article do not overlap, which is a good thing. Since ACS5 estimates are averages over the five years covered, overlapping survey periods would share years of underlying data, and the two estimates could not be treated as independent. Here, 2011 and 2012 separate the two windows, so no respondent appears in both.\n\nLastly, the data will be called in a wide format so that each tract in a given year has separate columns for the poverty and total counts. Since we are stacking data from two rounds, the data will then be pivoted wider again so that each tract is a single row with separate columns for the two time periods.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly2010 <- get_acs(geography = \"tract\", variables = c(below = \"B17001_002\", total = \"B17001_001\"),\n  state = \"PA\", county = \"Philadelphia\",  year = 2010, survey = \"acs5\", output = \"wide\")\n\nphilly2017 <- get_acs(geography = \"tract\", variables = c(below = \"B17001_002\", total = \"B17001_001\"),\n  state = \"PA\", county = \"Philadelphia\",  year = 2017, survey = \"acs5\", output = \"wide\")\n\nphilly <- bind_rows(\"2010\" = philly2010, \"2017\" = philly2017, .id = \"year\")\n\nphillywide <- pivot_wider(philly, id_cols = GEOID, names_from = year, values_from = c(belowE, belowM, totalE, totalM))\n```\n:::\n\n\n\n\nWe have loaded the data required to (almost) replicate the analysis. Before beginning, let us take a look at the broad characteristics of our dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly %>%\n  count(year) %>%\n  kable(col.names = c(\"ACS 5-year period\", \"Census tracts\"),\n        caption = \"Table 1. Census tracts retrieved for each survey period, Philadelphia County\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 1. Census tracts retrieved for each survey period, Philadelphia County\n\n|ACS 5-year period | Census tracts|\n|:-----------------|-------------:|\n|2010              |           384|\n|2017              |           384|\n\n\n:::\n:::\n\n\nBoth periods return the same 384 tracts, which means tract boundaries did not change between the two surveys and the tracts can be matched one to one by GEOID. We will also be working with ten variables, the names of which are presented below for the interested reader.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(phillywide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"GEOID\"       \"belowE_2010\" \"belowE_2017\" \"belowM_2010\" \"belowM_2017\"\n [6] \"totalE_2010\" \"totalE_2017\" \"totalM_2010\" \"totalM_2017\" \"NAME\"       \n```\n\n\n:::\n:::\n\n\n\n\n## Part 2\n\nWe first compute each tract's poverty rate and the margin of error of that rate. The margin of error of a proportion does not carry over from the margin of error of the count, because both the numerator and the denominator are themselves estimates. `moe_prop()` implements the Census Bureau's formula for combining them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide <- phillywide %>% \n  mutate(povpropE10 = belowE_2010/totalE_2010,\n         povpropE17 = belowE_2017/totalE_2017,\n         povpropM10 = moe_prop(belowE_2010, totalE_2010, belowM_2010, totalM_2010),\n         povpropM17 = moe_prop(belowE_2017, totalE_2017, belowM_2017, totalM_2017))\n```\n:::\n\n\nThe table below reports the unweighted mean of the tract-level rates. This is *not* the citywide poverty rate, and the difference matters. Averaging tract rates gives a 200-person tract the same weight as an 8,000-person tract. The correct citywide figure, computed by aggregating counts before dividing, appears in Part 3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide %>%\n  summarise(\"2006-10\" = round(mean(povpropE10, na.rm = TRUE)*100, 2),\n            \"2013-17\" = round(mean(povpropE17, na.rm = TRUE)*100, 2)) %>%\n  kable(caption = \"Table 2. Unweighted mean of tract-level poverty rates (%), shown for comparison only\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 2. Unweighted mean of tract-level poverty rates (%), shown for comparison only\n\n| 2006-10| 2013-17|\n|-------:|-------:|\n|   25.46|   26.15|\n\n\n:::\n:::\n\n\nThe coefficient of variation is calculated by dividing the standard error by the estimate and multiplying by 100 to turn it into a percentage. The ACS publishes margins of error at the 90% confidence level, which corresponds to a z-value of 1.645. We therefore calculate the standard error first by dividing the MOE by the z-value, then divide that by the estimate, and finally multiply by 100.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide <- phillywide %>%\n  mutate(cv10 = ((povpropM10/1.645)/povpropE10)*100,\n         cv17 = ((povpropM17/1.645)/povpropE17)*100)\n```\n:::\n\n\nAlong with computing the coefficient of variation, we categorise tracts by reliability using the Jurjevich et al. (2018) thresholds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide <- phillywide %>%\n  mutate(reliability10 = case_when(\n           cv10<12            ~ \"Reliable\",\n           cv10>=12 & cv10<40 ~ \"Somewhat reliable\",\n           cv10>=40           ~ \"Unreliable\",\n           is.na(cv10)        ~ \"Missing\"),\n         reliability17 = case_when(\n           cv17<12            ~ \"Reliable\",\n           cv17>=12 & cv17<40 ~ \"Somewhat reliable\",\n           cv17>=40           ~ \"Unreliable\",\n           is.na(cv17)        ~ \"Missing\")\n  )\n```\n:::\n\n\n### Reliability estimates\n\nThe table below shows how the tracts are distributed across the reliability classes. On the positive side, the share of unreliable tracts roughly halved between the two periods. On the negative, the share of tracts with genuinely reliable estimates remains very low: under 6 percent even in the later period. Seven tracts in 2006-10 and eight in 2013-17 have no computable rate at all.\n\nOne caution about the coefficient of variation: because it divides the margin of error by the estimate itself, a tract with a low poverty rate will appear unreliable even when its margin of error is modest in percentage-point terms. Part of the apparent improvement between the two periods may therefore reflect rising poverty rates rather than better precision.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreltable <- bind_rows(\n  phillywide %>% count(Reliability = reliability10) %>% mutate(Period = \"n2006\"),\n  phillywide %>% count(Reliability = reliability17) %>% mutate(Period = \"n2013\")\n) %>%\n  pivot_wider(names_from = Period, values_from = n) %>%\n  mutate(Reliability = factor(Reliability,\n           levels = c(\"Reliable\", \"Somewhat reliable\", \"Unreliable\", \"Missing\"))) %>%\n  arrange(Reliability) %>%\n  mutate(Flag = case_when(Reliability == \"Reliable\"          ~ \"+++\",\n                          Reliability == \"Somewhat reliable\" ~ \"++\",\n                          Reliability == \"Unreliable\"        ~ \"+\",\n                          Reliability == \"Missing\"           ~ \"-\"),\n         pct2006 = round(n2006/sum(n2006)*100, 1),\n         pct2013 = round(n2013/sum(n2013)*100, 1)) %>%\n  select(Flag, Reliability, n2006, pct2006, n2013, pct2013)\n\nkable(reltable,\n      col.names = c(\"Flag\", \"Reliability class\", \"Tracts\", \"% of tracts\", \"Tracts\", \"% of tracts\"),\n      caption = \"Table 3. Reliability of tract-level poverty rate estimates, Philadelphia (384 tracts). Columns 3-4 cover ACS 2006-10; columns 5-6 cover ACS 2013-17.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 3. Reliability of tract-level poverty rate estimates, Philadelphia (384 tracts). Columns 3-4 cover ACS 2006-10; columns 5-6 cover ACS 2013-17.\n\n|Flag |Reliability class | Tracts| % of tracts| Tracts| % of tracts|\n|:----|:-----------------|------:|-----------:|------:|-----------:|\n|+++  |Reliable          |     11|         2.9|     22|         5.7|\n|++   |Somewhat reliable |    321|        83.6|    332|        86.5|\n|+    |Unreliable        |     45|        11.7|     22|         5.7|\n|-    |Missing           |      7|         1.8|      8|         2.1|\n\n\n:::\n:::\n\n\nSymbols: `+++` reliable, `++` somewhat reliable, `+` unreliable, `-` no rate computable. Thresholds follow Jurjevich et al. (2018): a coefficient of variation below 12% is reliable, 12 to 40% somewhat reliable, and above 40% unreliable, where CV = (MOE / 1.645) / estimate × 100. Source: ACS 5-year estimates, table B17001.\n\n### Computing the change between the two periods and the margin of error of that change\n\nWe now investigate whether the poverty rate changed between the two periods, and if it did, whether the change is statistically significant or the kind of movement we might expect from sampling variation alone. There are three parts to this: first we estimate the change; second we calculate the margin of error of that change, following official Census Bureau guidance^1^; and third we test whether the change is distinguishable from zero.\n\nThe margin of error of a difference is the square root of the sum of the squared margins of error. Note that the squares are *added* even though the estimates are subtracted, because uncertainty accumulates in either operation. Since the 1.645 factors cancel, margins of error can be substituted directly for standard errors in this formula.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Estimating change in poverty rate\nphillywide$povratechangeE = phillywide$povpropE17 - phillywide$povpropE10\n\n# Step 2: Calculating the new MOE\nphillywide$povratechangeM = sqrt(phillywide$povpropM10^2 + phillywide$povpropM17^2)\n\nsummary(phillywide$povratechangeE*100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n-78.8068  -4.6506   1.1498   0.6473   6.7453  35.6606        8 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(phillywide$povratechangeM*100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  2.229   9.019  12.685  13.658  15.947 221.322       8 \n```\n\n\n:::\n:::\n\n\nThe estimates are noisy. The largest single drop is 78.8 percentage points and the largest margin of error is 221 percentage points. Both belong to tracts with very few residents, as the table below confirms: the tracts with the most extreme values hold between 53 and 2,154 people in the poverty universe, against a citywide average of roughly 3,900 per tract.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What is the mean number of people per tract in the two ACS5 rounds?\nmean(phillywide$totalE_2017)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3975.474\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(phillywide$totalE_2010)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3804.281\n```\n\n\n:::\n\n```{.r .cell-code}\nphillywide %>%\n  filter(povratechangeE < -.5 | povratechangeM > .25) %>%\n  select(totalE_2010, totalE_2017, povratechangeE, povratechangeM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  totalE_2010 totalE_2017 povratechangeE povratechangeM\n        <dbl>       <dbl>          <dbl>          <dbl>\n1         654         450         -0.192          0.348\n2         500         967          0.133          0.298\n3        1870        2154         -0.345          0.268\n4         407         800         -0.488          0.291\n5         677         182         -0.788          0.235\n6          67          98          0.133          1.63 \n7          68          53          0.233          2.21 \n```\n\n\n:::\n:::\n\n\n### Testing whether the change is statistically significant\n\nOn a naive reading, the poverty rate at the tract level rose on average by 0.65 percentage points between the two ACS5 rounds. At the extremes, one tract shows an increase of 35.7 percentage points and another a drop of 78.8 points. The question is whether these movements reflect real change or sampling variation: if the ACS had happened to sample different households in each tract, would the estimates have come out very differently? To answer this, we implement a z-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide <- phillywide %>%\n  mutate(\n    ztest = povratechangeE/(povratechangeM/1.645),\n    siglevel = if_else(ztest > 1.645 | ztest < -1.645, 1, 0)\n  )\n\ncount(phillywide, siglevel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  siglevel     n\n     <dbl> <int>\n1        0   313\n2        1    63\n3       NA     8\n```\n\n\n:::\n:::\n\n\nThe test shows that 63 tracts (~17%) out of 376 with valid poverty data in both periods register a change distinguishable from zero at 90% confidence. Among those 63, the rate increased in 36 tracts and decreased in 27, so the detectable movement runs in both directions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide %>%\n  filter(siglevel == 1) %>%\n  mutate(Direction = if_else(povratechangeE > 0, \"Increase\", \"Decrease\")) %>%\n  count(Direction) %>%\n  kable(col.names = c(\"Direction of change\", \"Tracts\"),\n        caption = \"Table 4. Direction of change among the 63 tracts whose change is distinguishable from zero at 90% confidence\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 4. Direction of change among the 63 tracts whose change is distinguishable from zero at 90% confidence\n\n|Direction of change | Tracts|\n|:-------------------|------:|\n|Decrease            |     27|\n|Increase            |     36|\n\n\n:::\n:::\n\n\nThe figure below plots every tract's estimated change together with its margin of error. The dashed line marks zero: wherever a tract's error bar crosses it, the data cannot establish that the rate changed at all.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotdata <- phillywide %>%\n  filter(!is.na(povratechangeE)) %>%\n  mutate(rank = rank(povratechangeE),\n         Significance = if_else(siglevel == 1,\n                                \"Distinguishable from zero\",\n                                \"Not distinguishable from zero\"))\n\nggplot(plotdata, aes(x = rank, y = povratechangeE*100,\n                     ymin = (povratechangeE - povratechangeM)*100,\n                     ymax = (povratechangeE + povratechangeM)*100,\n                     colour = Significance)) +\n  geom_pointrange(size = 0.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  coord_cartesian(ylim = c(-100, 100)) +\n  labs(\n    title = \"Change in tract poverty rate, Philadelphia, 2006-10 to 2013-17\",\n    subtitle = \"Each tract's estimated change with its 90% margin of error\",\n    x = \"Census tracts, ordered by size of estimated change\",\n    y = \"Change in poverty rate (percentage points)\",\n    colour = \"At 90% confidence\",\n    caption = \"Source: ACS 5-year estimates, table B17001. Vertical bars are 90% margins of error.\\nAxis limited to +/-100 points; two very small tracts fall outside this range.\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](assignment3_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe uncertainty is not spread evenly across the city. It is concentrated in tracts with few residents, as the next figure shows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide %>%\n  filter(!is.na(povratechangeM)) %>%\n  ggplot(aes(x = totalE_2017, y = povratechangeM*100)) +\n  geom_point(alpha = 0.5) +\n  geom_hline(yintercept = 12.7, linetype = \"dashed\") +\n  coord_cartesian(ylim = c(0, 60)) +\n  labs(\n    title = \"Small tracts produce the least certain estimates\",\n    subtitle = \"Margin of error on the 2006-10 to 2013-17 change, against tract population.\\nDashed line marks the median margin of error of 12.7 percentage points\",\n    x = \"People in the poverty universe, 2013-17\",\n    y = \"Margin of error on the change (percentage points)\",\n    caption = \"Source: ACS 5-year estimates, table B17001.\\nAxis limited to 60 points; two very small tracts fall outside this range.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](assignment3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n### What are the missing values?\n\nWe now look at the tracts for which no rate can be computed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide %>%\n  summarise(na_2010 = sum(is.nan(povpropE10)),\n            na_2017 = sum(is.nan(povpropE17)),\n            na_both = sum(is.nan(povpropE10) & is.nan(povpropE17)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  na_2010 na_2017 na_both\n    <int>   <int>   <int>\n1       7       8       7\n```\n\n\n:::\n\n```{.r .cell-code}\nphillywide %>%\n  filter(is.nan(povpropE10) & is.nan(povpropE17)) %>%\n  select(GEOID, NAME)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  GEOID       NAME                                                \n  <chr>       <chr>                                               \n1 42101005000 Census Tract 50, Philadelphia County, Pennsylvania  \n2 42101980300 Census Tract 9803, Philadelphia County, Pennsylvania\n3 42101980400 Census Tract 9804, Philadelphia County, Pennsylvania\n4 42101980500 Census Tract 9805, Philadelphia County, Pennsylvania\n5 42101980700 Census Tract 9807, Philadelphia County, Pennsylvania\n6 42101980800 Census Tract 9808, Philadelphia County, Pennsylvania\n7 42101980900 Census Tract 9809, Philadelphia County, Pennsylvania\n```\n\n\n:::\n:::\n\n\nSeven tracts have no rate in either period. Checking their boundaries against Census and mapping sources identifies them as:\n\n- three covering Philadelphia International Airport (42101980300, 42101980400 and 42101980900)\n- the Navy Yard and port peninsula in South Philadelphia (42101005000) and riverfront land along the Delaware (42101980700)\n- a golf course (42101980800)\n- Hunting Park (42101980500)\n\nOne further tract, 42101980600, has a rate in 2006-10 but not in 2013-17. It covers the South Philadelphia sports complex, and the small residential population recorded in the earlier period had disappeared from the estimates by the later one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywide %>%\n  filter(is.nan(povpropE17)) %>%\n  select(NAME, GEOID)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  NAME                                                 GEOID      \n  <chr>                                                <chr>      \n1 Census Tract 50, Philadelphia County, Pennsylvania   42101005000\n2 Census Tract 9803, Philadelphia County, Pennsylvania 42101980300\n3 Census Tract 9804, Philadelphia County, Pennsylvania 42101980400\n4 Census Tract 9805, Philadelphia County, Pennsylvania 42101980500\n5 Census Tract 9806, Philadelphia County, Pennsylvania 42101980600\n6 Census Tract 9807, Philadelphia County, Pennsylvania 42101980700\n7 Census Tract 9808, Philadelphia County, Pennsylvania 42101980800\n8 Census Tract 9809, Philadelphia County, Pennsylvania 42101980900\n```\n\n\n:::\n:::\n\n\nThese eight tracts do not have missing data in the ordinary sense. Each has no one in the poverty universe, so the rate is a division of zero by zero and is mathematically undefined rather than unobserved. No imputation is appropriate and there is nothing to recover. We therefore exclude all eight from the analysis of change, leaving 376 tracts.\n\nThis is a different problem from a tract with a small but non-zero population. Those tracts have defined rates that happen to be very imprecise, and they are retained: the coefficient of variation and the significance test are what handle them.\n\n## Part 3: Adjudicate\n\nWe now sort the article's claims into three buckets: supported, not supported, and undetermined.\n\n\n\n**Supported.** The city's 26 percent poverty rate for 2013-17 holds up. Aggregating counts across all tracts before dividing gives 25.8 percent, with a margin of error of plus or minus 0.5 percentage points. That interval is far tighter than any individual tract's, because a citywide estimate pools the entire sample. The article's characterisation of Philadelphia as a high-poverty city is accurate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphillywidestats %>%\n  summarise(\"2006-10 rate\" = round(rate10*100, 2),\n            \"2006-10 MOE\" = round(rate10_moe*100, 2),\n            \"2013-17 rate\" = round(rate17*100, 2),\n            \"2013-17 MOE\" = round(rate17_moe*100, 2),\n            \"Change\" = round(change*100, 2),\n            \"MOE of change\" = round(change_moe*100, 2),\n            \"Z-value\" = round(z, 2)) %>%\n  kable(caption = \"Table 5. Citywide poverty rate, Philadelphia, in percent and percentage points. Rates are computed by aggregating tract counts, not by averaging tract rates. Margins of error are at 90% confidence, and a z-value above 1.645 would indicate a change distinguishable from zero.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 5. Citywide poverty rate, Philadelphia, in percent and percentage points. Rates are computed by aggregating tract counts, not by averaging tract rates. Margins of error are at 90% confidence, and a z-value above 1.645 would indicate a change distinguishable from zero.\n\n| 2006-10 rate| 2006-10 MOE| 2013-17 rate| 2013-17 MOE| Change| MOE of change| Z-value|\n|------------:|-----------:|------------:|-----------:|------:|-------------:|-------:|\n|        25.08|        0.54|         25.8|        0.52|   0.72|          0.74|     1.6|\n\n\n:::\n:::\n\n\n**Not supported.** The article opens by describing a city \"still not recovered from the Great Recession\" and quotes an economist on poverty continuing to rise robustly. The data do not show a rise. The citywide rate moved from 25.1 percent in 2006-10 to 25.8 percent in 2013-17, an increase of 0.72 percentage points against a margin of error of plus or minus 0.74 points. The resulting z-value of 1.60 falls short of the 1.645 threshold for 90 percent confidence, so the change cannot be distinguished from sampling variation. The defensible finding is that poverty stayed high, not that it worsened.\n\nThe tract-level picture is likewise mixed rather than uniformly deteriorating. Of the 376 tracts with a defined rate in both periods, only 63 (17 percent) show a change distinguishable from zero. The median tract moved 1.1 percentage points against a median margin of error of plus or minus 12.7 points. Among the 63 detectable changes, 36 were increases and 27 were decreases. The article's description of Eastwick as showing \"the greatest poverty-rate increase of any community\" is a ranking claim, and rankings are the first thing to break under uncertainty of this magnitude: with error bars this wide, the data cannot identify a single worst-affected place.\n\n**Undetermined.** Every named-neighborhood figure is unverifiable. The Inquirer aggregated census tracts into neighborhoods of its own drawing and never published which tracts went into which neighborhood, so Fairhill's 61 percent and Eastwick's rise from 12 to 26 percent can be neither reproduced nor falsified. Any boundary drawn here would be my construction rather than theirs.\n\nThe Holmesburg (2 to 19 percent) and Mayfair (1 to 14 percent) figures carry an additional ambiguity. Both appear in a section about white poverty, which suggests they are white-alone rates drawn from table B17001A rather than the overall rates used elsewhere in the article. A 2 percent overall poverty rate for a Philadelphia neighborhood would be implausible. The article never specifies which measure it is using, so the claims cannot be evaluated.\n\nFinally, the income comparisons mix survey vintages. A 2013-17 five-year median of \\$39,759 is set against \"\\$41,449 between 2016 and 2017,\" and a one-year 2016-to-2017 white poverty figure is folded into an argument otherwise built on five-year estimates. Estimates from different ACS products are not directly comparable, and without knowing which series the article intends, the comparison cannot be assessed.\n\n## Part 4 — Rewrite\n\nA new federal survey finds that roughly one in four Philadelphians lived in poverty between 2013 and 2017, a rate that has barely moved since the years spanning the Great Recession. The citywide figure is solid. The neighborhood-level story is harder to pin down.\n\nThe American Community Survey reaches only a small sample in any one census tract, so estimates for small areas carry wide margins of error, typically around 13 percentage points when two periods are compared. Of 376 Philadelphia tracts, only 63 show a change large enough to separate from sampling noise, and those run in both directions. Some areas clearly got poorer; others clearly improved; most cannot be told apart from where they started.\n\nPoverty in Philadelphia remains stubbornly high. Which specific blocks are worst off, and which are sliding fastest, is a question this data answers less confidently than the numbers suggest.\n\n## Endnotes\n\n^1^ https://www2.census.gov/programs-surveys/acs/tech_docs/statistical_testing/2021_Instructions_for_Stat_Testing_ACS.pdf\n",
    "supporting": [
      "assignment3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}