{
  "hash": "1eb1ca9a0b18793d4b91e96e5ab7ff14",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Abishek Nippani\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\nIn this analysis, I look at **median gross rent across counties in New York**, and\nask which communities we measure most and least reliably. I have chosen to look at\nthe median gross rent people pay in New York as the state has the highest average\nrental costs in the world. I'm curious to see how this average changes across different\ncounties and regions of the state.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"36\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25064_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 36001 Albany County, New York      B25064_001     1252    22\n2 36003 Allegany County, New York    B25064_001      754    33\n3 36005 Bronx County, New York       B25064_001     1436    11\n4 36007 Broome County, New York      B25064_001      914    26\n5 36009 Cattaraugus County, New York B25064_001      759    30\n6 36011 Cayuga County, New York      B25064_001      895    39\n```\n\n\n:::\n:::\n\n\nThe dataframe has 62 rows, which matches the number of counties in the state New York.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                        estimate   moe moe_pct\n   <chr>                          <dbl> <dbl>   <dbl>\n 1 Hamilton County, New York        860    95   11.0 \n 2 Schuyler County, New York        858    75    8.74\n 3 Greene County, New York          993    79    7.96\n 4 Lewis County, New York           821    59    7.19\n 5 Orleans County, New York         877    60    6.84\n 6 Yates County, New York           802    46    5.74\n 7 Wyoming County, New York         782    44    5.63\n 8 Cortland County, New York        911    50    5.49\n 9 Chenango County, New York        819    44    5.37\n10 Livingston County, New York      912    48    5.26\n```\n\n\n:::\n:::\n\n\n\nHamilton County has the largest margin of error relative to its estimate. The raw\nMOE is 95, while the MOE percentage relative to its estimate is 11.04.\n\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    51\n2 Low confidence      1\n3 Moderate           10\n```\n\n\n:::\n:::\n\n\n\n51 counties fall into high confidence, 10 into moderate confidence and 1 into low confidence.\n\n## Is the margin of error bigger in small places?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 36001 Albany County, New York        1252     22  315374    NA\n2 36003 Allegany County, New York       754     33   47027    NA\n3 36005 Bronx County, New York         1436     11 1419250    NA\n4 36007 Broome County, New York         914     26  197738    NA\n5 36009 Cattaraugus County, New York    759     30   76479    NA\n6 36011 Cayuga County, New York         895     39   75464    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         51        381479.\n2 Low confidence           1          5102 \n3 Moderate                10         41178.\n```\n\n\n:::\n:::\n\n\nBased on the size of the margin of error relative to its estimate (moe_pct), three buckets of reliability\nwere created: *high confidence* (moe_pct<5), *moderate confidence* (moe_pct<10) and \n*low confidence* (moe_pct>=10). 51 counties fall into high confidence, 10 into moderate\nand 1 into low confidence. \n\nA clear pattern can be observed across the three buckets: as me move from high to moderate\nto low confidence, the average population of these counties also falls. \n\nSpecifically, the average population of high confidence counties is 381,479,\n41,178 for moderate confidence counties, and 5,102 for the low confidence one.\n\nThe data seems to suggest that smaller counties may be more likely to have higher\nmargin of error relative to the underlying estimate.\n\n\n## What this means for policy\n\nWhen looking at county-wise median gross rental payments in the state of New York, \nwe know the least about Hamilton County. This is based on the size of the margin \nof error relative to its corresponding estimate. Hamilton County has both the \nhighest margin of error in absolute terms and the highest margin of error relative \nto the estimate: an MOE of 95 and an MOE of 11% relative to the estimate. \n\nThis is a function of its small population size and the sampling strategy used \nin the ACS. Data for the present analysis is drawn from ACS, which is based on \nsample surveys. These surveys draw smaller samples from less populous counties \nand larger samples from more populous ones. Counties such as Putnam County or \nGreene County have an MOE of 80 and 79, respectively, but their MOE percentages \nare 4.4 and 7.96, respectively. While their MOEs are 84% (Putnam) and 83% (Greene) \nof Hamilton's, their MOE percentages are only 40% and 72% of Hamilton. \nThis is because their respective populations are substantially bigger than \nHamilton's 5,102 people -- with Putnam at 97,988 and Greene at 48,554. \n\nIf the state of New York or federal agencies were to use data from the ACS to \ndevise policies related to rental housing, then it could be very inaccurate for \nsmaller counties such as Hamilton County. Specifically, if the estimate reflects the \nlower end of the true rent being paid in Hamilton, then policies would end up \nunderserving people who pay higher rents. Thus, before any action is taken, it \nwould be advisable to conduct specific surveys in smaller counties or triangulate \nthe estimate with county-specific administrative data.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}